### ISSUE TITLE
Moulder with Graphical Library

### ISSUE THREAD

**Issue by santisoler** [fatiando/moulder#1]
It's great to have a new repo for Moulder.

I was thinking to use some graphical libraries to expand the capabilities.
I've experienced with GTK+ libraries in the past, but I don't know if it would be a good choice in order to ensure multiplatform compatibility.
Is there any graphical library that can be used in GNU/Linux, Mac OSX and Windows?

**Comment by leouieda** [comment]
That would be good. I have no experience with Python GUIs but from https://docs.python.org/3/faq/gui.html it seems that tkinter is the default. GTK should be cross-platform as well but it might be difficult to get installed everywhere. I couldn't find any conda-forge recipes for GTK or wxPython (which seemd like a good alternative).

It might be better to use tk since it comes with Python. It might save us a lot of headaches.

**Comment by santisoler** [comment]
What about PyQt5? It comes with Anaconda and I think it's a more powerful and robust tool.

Although I'm a GNU/Linux user, I've found [this PyQt tutorial under Windows](http://pythonforengineers.com/your-first-gui-app-with-python-and-pyqt/), so I think that we won't have many headaches with multiplatform support.

**Comment by santisoler** [comment]
Hi @leouieda!

I've been experiencing with PyQt5. It's really easy  to build very cool GUI with it. I think is more intuitive that Tkinter, although it lacks of a good documentation (most docs are for C++ and Qt5, but the classes and methods are called the same way in PyQt5).

I have an already working [draft](https://www.github.com/santis19/moulder) of what moulder could look like under PyQt5. It's working with the commit [e6fd003](https://github.com/fatiando/fatiando/pull/415/commits/e6fd003fee2355706a8891fd6a682406f3423f2d) of fatiando, in the [santis19:polygon_orientation](https://github.com/santis19/fatiando/tree/polygon_orientation) branch.

I cannot make a PR on fatiando/moulder, I think due to it's empty so I can't fork it.

**Comment by leouieda** [comment]
@santis19 great!

For some reason, you didn't have write access to this repository. Weird. I added you to the core team and gave access to the repository. You should be able to push directly to this repo now. Please feel free to do so.

I'm fine with whatever technology you think will work best.

**Comment by santisoler** [comment]
@leouieda thanks!

I'll get into it.
